name: code-quality
on:
  workflow_call:
    inputs:
      node-version: { default: '20', type: string }
      package-path: { required: true, type: string }
jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: code-checkout
        uses: actions/checkout@v7
      - name: npm setup
        uses: actions/setup-node@v6
        with:
          node-version: ${{ inputs.node-version }}
          cache-dependency-path: ${{ inputs.package-path }}
          cache: npm
      - name: npm install
        run: npm install
        working-directory: ${{ inputs.package-path }}
      - name: linting-code
        run: npm run lint
        working-directory: ${{ inputs.package-path }}
        
