name: Devsecops-deploy.yml
on:
  workflow_run:
    workflows: [merge]
    types: completed
    
jobs:
  deploy-app:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

  OWASP-ZAP-scan:
    needs: deploy-app
    uses: ./.github/workflows/OWASP_DAST.yml
    secrets: inherit
