name: main
on: 
  push:
    branches: master

jobs:
  build-test-frontend:
    uses: ./.github/workflows/reusable-node-build-test.yml
    with:
      node-version: '22' 
      package-path: 'frontend' 
      run_tests: true
  build-test-backend:
    uses: ./.github/workflows/reusable-go-build-test.yml
    with:
      go-version: '1.23' 
      go-version-file: backend/go.mod
      cache-dependency-path: backend/go.sum
      code-path: backend
      
  docker:
    needs: [build-test-frontend, build-test-backend]
    strategy:
      matrix:
        repo: [ 'frontend', 'backend' ]
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image-name: devboard-${{ matrix.repo }}
      tag: latest
      docker-name: rohit5126
      context: ${{ matrix.repo }}
    secrets: 
      docker_username: ${{ vars.DOCKER_USER }}
      docker_password: ${{ secrets.DOCKER_TOKEN }}
    
    
  deploy:
     needs: [docker]
     runs-on: self-hosted
     steps:
       - name: code
         uses: actions/checkout@v6
       - name: docker deploy
         run: |
           cp .env.example .env
           docker compose up
 
  
    
