name: main
on:
  push: 

jobs:
  frontend-code-quality:
    uses: ./.github/workflows/Node-code-quality.yml
    with:
      node-version: 20
      package-path: frontend/package-lock.json
      code-path: frontend/
  backend-code-quality:
    uses: ./.github/workflows/Go-code-quality.yml
    with:
      go-version: '1.23'
      go-version-file: backend/go.mod
      cache-dependency-path: backend/go.sum
      code-path: backend/
  secret-scanner:
    uses: ./.github/workflows/secret-scanning.yml

  dependency-check:
    uses: ./.github/workflows/security-check.yml
    with:
      backend_workdir: backend
      frontend_workdir: frontend

  docker-lint:
    uses: ./.github/workflows/docker-lint.yml
    with:
      frontend-dockerfile-dir: frontend
      backend-dockerfile-dir: backend
      
