name: pr-pipeline
on:
  pull_request:
    branches: [master]
    types: [opened, synchronize]
  workflow_dispatch:
  push:
    paths: ./.github/workflows/pr-pipeline.yml
    

jobs:
  job1:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      node-version: '22' 
      package-path: 'frontend' 
      run_tests: true

  job2:
    needs: job1
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: print
        run: echo " PR checks passed for branch: ${{ github.head_ref }} "
      
    
    
        
