name: docker-reuse
on:
  workflow_call:
    outputs:
      image:
        description: "the image name"
        value: ${{ jobs.docker-build.outputs.out2 }}
    inputs:
      image-name: { required: true, type: string }
      tag: {required: false, default: latest, type: string }
      docker-name: { required: true, type: string }
    secrets:
      docker_username: { required: true }
      docker_password: { required: true }
  
      
jobs:   
  docker-build:
    outputs:
      out2: ${{ steps.image.outputs.image-url }}
    runs-on: ubuntu-latest
    steps:
      - name: code
        uses: actions/checkout@v6
      - name: docker login
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}

      - name: docker-build
        id: build
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: ${{ inputs.docker-name }}/${{ inputs.image-name }}:${{ inputs.tag }}
      - name: image-id
        id: image
        run: |
          echo "image-url={{ inputs.docker-name }}/${{ inputs.image-name }}:${{ inputs.tag }}" >> "$GITHUB_OUTPUT"
      
        
          
      
