name: go-build-test
on: 
  workflow_call:
    inputs:
      go-version: { default: '1.23', type: string } 
      go-version-file: { required: true, type: string }
      cache-dependency-path: { required: true, type: string }
      code-path: { required: true, type: string }
  
jobs:
  go-build-test:
      runs-on: ubuntu-latest
      steps:
        - name: code-setup
          uses: actions/checkout@v6
          
        - name: go-steup
          uses: actions/setup-go@v6
          with:
            go-version: ${{ inputs.go-version }}
            go-version-file: ${{ inputs.go-version-file }}
            cache-dependency-path: ${{ inputs.cache-dependency-path }}
        - name: run go-format
          run: go fmt main.go
          working-directory: ${{ inputs.code-path }}
        - name: run go-vet
          run: go vet main.go
          working-directory: ${{ inputs.code-path }}

        - name: testing
          run: go test
          working-directory: ${{ inputs.code-path }}
        
      
