name: dependency-check
on: 
  push: 
permissions:
  contents: write
  security-events: read
jobs:
  dependecy-check:
    runs-on: ubuntu-latest
    permissions:
      repository-projects: read
    steps:
      - name: code
        uses: actions/checkout@v7
        
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.22'
          go-version-file: backend/go.mod
          cache-dependency-path: backend/go.sum
      - name: Run govulncheck and export report
        uses: golang/govulncheck-action@v1
        with:
          output-format: sarif
          output-file: govulncheck-results.sarif
          work-dir: backend/

      - name: Upload results to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Go-vulnerabilities-report
          path: govulncheck-results.sarif
          retention-days: 7

