name: Sonar-Scan
on: 
  workflow_call:
    inputs:
      SONAR_HOST_URL: { required: true,type: string }
    secrets:
      SONAR_TOKEN: { required: true }
      

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    steps:
      - name: code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v8.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ inputs.SONAR_HOST_URL }}
